# Generated by Django 4.1.8 on 2024-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=250)),
                ('Book_Author', models.CharField(blank=True, max_length=250, null=True)),
                ('Book_Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Book_Category', models.CharField(blank=True, max_length=1000, null=True)),
                ('Genratedate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
