# Generated by Django 4.1.8 on 2024-02-26 09:02

import Reader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0002_addbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbook',
            name='Book_Coverpage',
            field=models.FileField(blank=True, null=True, upload_to=Reader.models.upload_Book_path),
        ),
        migrations.AddField(
            model_name='addbook',
            name='Book_Upload',
            field=models.FileField(blank=True, null=True, upload_to=Reader.models.upload_Book_path),
        ),
    ]
